import type { FieldConfig } from '../DynamicFields';

export const companyFields: FieldConfig[] = [
  {
    title: 'Company Business ID',
    name: 'companyBizId',
    type: 'text',
    placeholder: 'Enter company business ID',
    required: true,
    className: 'col-span-1',
  },
  {
    title: 'Company Name',
    name: 'companyName',
    type: 'text',
    placeholder: 'Enter company name',
    required: true,
    className: 'col-span-1',
  },
  {
    title: 'Company Type',
    name: 'companyTypeId',
    type: 'dropdown',
    options: [],
    required: true,
    className: 'col-span-1',
  },
  {
    title: 'Company Category',
    name: 'companyCategoryId',
    type: 'dropdown',
    options: [],
    required: true,
    className: 'col-span-1',
  },
  {
    title: 'Company Cin',
    name: 'companyCin',
    type: 'text',
    placeholder: 'Enter company CIN',
    required: true,
    className: 'col-span-1',
  },
  // {
  //   title: 'Company parent company ID',
  //   name: 'companyParentCompanyId',
  //   type: 'text',
  //   placeholder: 'Enter company parent company ID',
  //   required: true,
  //   className: 'col-span-1',
  // },
  {
    title: 'About Company',
    name: 'companyAboutus',
    type: 'textarea',
    placeholder: 'Enter company description',
    required: true,
    className: 'col-span-2',
  },
  {
    title: 'Active',
    name: 'active',
    type: 'dropdown',
    options: [
      { label: 'Yes', value: 'Y' },
      { label: 'No', value: 'N' },
    ],
    required: true,
    className: 'col-span-1',
  },
];
